_parent_: options/base.yaml

group: Glue                                                 # name of experiment group
c2f:
arch:                                                       # architectural optionss
    layers_feat: [null,256,256,256,256,256,256,256,256]     # hidden layers for feature/density MLP]
    layers_rgb: [null,128,3]                         # hidden layers for color MLP]
    layers_trans: [null,256,256,256,5]                      # hidden layers for trasient color and density MLP]
    skip: [4]                                               # skip connections
    posenc:                                                 # positional encoding:
        L_3D: 10                                             # number of bases (3D point)
#        L_3D_rgb: 2
        L_view: 4                                           # number of bases (viewpoint)
    density_activ: softplus                                 # activation function for output volume density
    tf_init: true                                           # initialize network weights in TensorFlow style

nerf:                                                       # NeRF-specific options
    view_dep: true                                          # condition MLP on viewpoint
    depth:                                                  # depth-related options
        param: metric                                       # depth parametrization (for sampling along the ray)
        range: [0.5, 2.0]                                     # near/far bounds for depth sampling, measured in *meter* unit
        scale: 10                                           # Transform to other metric (such as dm) for pose and depth,  which stored as m for default
        range_source:
        box_mask:

    sample_intvs: 64                                        # number of samples
    sample_stratified: true                                 # stratified sampling
    fine_sampling: false                                    # hierarchical sampling with another NeRF
    sample_intvs_fine:                                      # number of samples for the fine NeRF
    rand_rays: 2048                                         # number of random rays for each step
    ray_obj_ratio: 0.0                                     # number of rays sampled on CAD models
    density_noise_reg:                                      # Gaussian noise on density output as regularization
    setbg_opaque:                                           # fill transparent rendering with known background color (Blender only)
    mask_obj: true
    N_latent: 32
    N_latent_trans: 16
    N_latent_light: 48
    min_uncert: 0.05

data:                                                       # data options
    dataset: lm                                             # dataset name
    object: glue                                            # scene name
    scene: scene_all
    image_size: [128,128]                                   # input image sizes [height,width]
    num_workers: 4                                          # number of parallel workers for data loading
    preload: true                                           # preload the entire dataset into the memory
    bgcolor:                                                # background color (Blender only)
    val_on_test: False
    val_sub:
    pose_source: predicted
    pose_loop: init
    erode_mask: false
    erode_mask_loss:

camera:                                                     # camera options
    model: perspective                                      # type of camera model
    ndc: false                                              # reparametrize as normalized device coordinates (NDC)

loss_weight:                                                # loss weights (in log scale)
    render: 0                                               # RGB rendering loss
    depth:
    mask:
    uncert:
    trans_reg:
    entropy:
    consis3d:
    render_fine:                                            # RGB rendering loss (for fine NeRF)

optim:                                                      # optimization options
    lr: 1.e-3                                               # learning rate (main)
    lr_end: 1.e-4                                           # terminal learning rate (only used with sched.type=ExponentialLR)
    sched:                                                  # learning rate scheduling options
        type: ExponentialLR                                 # scheduler (see PyTorch doc)
        gamma:                                              # decay rate (can be empty if lr_end were specified)

batch_size:                                                # batch size (not used for NeRF/BARF)
max_epoch:                                                  # train to maximum number of epochs (not used for NeRF/BARF)
max_iter: 200000

freq:                                                             # periodic actions during training
    scalar: 100                                            # log losses and scalar states (every N iterations)
    vis: 1000                                              # visualize results (every N iterations)
    val: 1000                                               # validate on val set (every N iterations)
    ckpt: 5000                                             # save checkpoint (every N iterations)
